### ISSUE TITLE
Error in .normarg_seqlevels(seqnames)

### ISSUE THREAD

**Issue by monmt** [rchereji/plot2DO#13]
Hi! I was using this package and I found some troubles...

Im using this bam file that contain this @SQ:
@SQ SN:I LN:5579133
@SQ  SN:II LN:4539804
@SQ  SN:III LN:2452883
@SQ  SN:MT LN:19431
@SQ  SN:MTR LN:20128
@SQ  SN:AB325691  LN:20000

Im using this command:
 Rscript plot2DO.R --file=RF14_0_A.bam --genome=EF2

And it throws this error:
Error in .normarg_seqlevels(seqnames) : 
 supplied 'seqlevels' cannot contain NAs or empty strings ("")
Calls: Main ... BuildReadsGRangesFromBAM -> Seqinfo -> .normarg_seqlevels

How can I solve it?

Thanks in advance!

**Comment by etiennedanis** [comment]
Hi monmt,
I got the same error.
I added the index .bai file for each bam file to the same directory and I am not getting the error anymore. 
Have you tried that?

**Comment by rchereji** [comment]
seems like a problem with the input bam file...

**Comment by Liang7094** [comment]
> Hi! I was using this package and I found some troubles...
> 
> Im using this bam file that contain this @sq: @sq SN:I LN:5579133 @sq SN:II LN:4539804 @sq SN:III LN:2452883 @sq SN:MT LN:19431 @sq SN:MTR LN:20128 @sq SN:AB325691 LN:20000
> 
> Im using this command: Rscript plot2DO.R --file=RF14_0_A.bam --genome=EF2
> 
> And it throws this error: Error in .normarg_seqlevels(seqnames) : supplied 'seqlevels' cannot contain NAs or empty strings ("") Calls: Main ... BuildReadsGRangesFromBAM -> Seqinfo -> .normarg_seqlevels
> 
> How can I solve it?
> 
> Thanks in advance!

How did you solve it? I encountered the same error. Thank you!
![Image_1721876122936](https://github.com/user-attachments/assets/a6df57a2-82f1-4eb0-ad09-e44230962d44)
