### ISSUE TITLE
Error in seq.default(min(lengthHist), 1.05 * max(lengthHist), 1)

### ISSUE THREAD

**Issue by sidkalra512** [rchereji/plot2DO#15]
I have a BAM file generated after aligning the reads to sacCer3. I tried running plot2D on this file for TTS with default parameters and encountered this error message 

```
Error in seq.default(min(lengthHist), 1.05 * max(lengthHist), 1) : 
  'from' must be a finite number
Calls: Main -> PlotFigure
```
Any suggestions on how to resolve this?

**Comment by ajtonsager** [comment]
Hello -- I'm also having this issue. Has anyone come to a solution here?

**Comment by paulati** [comment]
Hi, the problem is min(lengthHist), maybe lengthHist is null so min(lengthHist) is not a finite number. 
The most common reason related to this error is that the input data has not been loaded correctly.
If you want to share some data and the parameters you are using, I can try to debug the error.
Best, Paula

**Comment by ajtonsager** [comment]
Does the issue happen to arise from the input BAM generated from single-ended sequencing data? Currently all of my paired-ended data aligned with HISAT2 works well with plot2DO, but none of my single-ended is working. I'm happy to share a BAM too if that's helpful.

Drew

**Comment by rchereji** [comment]
Yes, this tool can only be used with paired-end sequencing data. There's no information about DNA fragment length stored in the BAM/SAM files for single-end reads, so one cannot compute the coverage/occupancy of the full DNA fragments, as one of the ends was lost in the sequencing process...
