### ISSUE TITLE
the questions about the input bam file?

### ISSUE THREAD

**Issue by liuyu988** [rchereji/plot2DO#16]
hi, thanks for your brilliant software!
I decide to learn the analysis of Mnase-seq data recently and want to detect the nuclesome occupancy.
I am confused with the input file. why is always the average value 1 in your example figures? and  need to normlize my bam file firstly? and how to normalize?
thanks a lot!
YU

**Comment by paulati** [comment]
Hi Yu,
max average occupancy value is not always 1, in the example figures some of them are bigger.
You don't need to normalize the input bam file.
Best, 
Paula

**Comment by rchereji** [comment]
No need to normalize the occupancy on your own, this is done automatically by plot2DO. It basically plots the occupancy near some relevant sites (e.g. TSS) relative to the average occupancy in your window of interest (e.g. [TSS-1000, TSS+1000]).
