### ISSUE TITLE
Errors in ploting dyads

### ISSUE THREAD

**Issue by jeff-godwin** [rchereji/plot2DO#17]
Hello team,

I'm facing an issue while plotting dyad density (the occupancy plots come out fine). 
My data is from MNase-seq in yeast.

The error messages are -
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘coverage’ for signature ‘"NULL"’
Calls: Main ... ComputeNormalizationFactors -> coverage -> <Anonymous>

Could you please let me know what could be the issue?
I can provide other information as required.

Many thanks,
Jeff

**Comment by paulati** [comment]
Hi Jeffrey,

based on the error, it looks like the reads are NULL.

You get reads object from input file path, genome name, and annotations:

	rawReads <- LoadReads(params$inputFilePath, params$genome, annotations)
  
	reads <- CleanReads(rawReads, annotations$chrLen, params$lMin, params$lMax)

Then, you call ComputeNormalizationFactors with reads as parameter:

	ComputeNormalizationFactors <- function(reads)  {
		occ <- coverage(reads)
  
If you want to share raw data and annotations with me, I can debug it.

Best,
Paula

**Comment by jeff-godwin** [comment]
Hi Paula,
Thanks for the reply.
I have managed to troubleshoot the problem. It was coming from an issue with the BAM file index. It had been overwritten by the script. 

Thanks,
Jeff
