### ISSUE TITLE
Error: Unexpected format to the list of available marts.

### ISSUE THREAD

**Issue by willluo123** [rchereji/plot2DO#18]
Hi,
When I was using -g mm10, an error took place like this:

Error: Unexpected format to the list of available marts.
Please check the following URL manually, and try ?listMarts for advice.
http://may2012.archive.ensembl.org:80/biomart/martservice?type=registry&requestid=biomaRt
In addition: Warning message:
Ensembl will soon enforce the use of https.
Ensure the 'host' argument includes "https://"
Execution halted

I tried to change the host path of mm10 in annotation_config.yaml. However, another error took place, as following:
Error in martCheck(mart) :
  No dataset selected, please select a dataset first.  You can see the available datasets by using the listDatasets function see ?listDatasets for more information.  Then you should create the Mart object by using the useMart function.  See ?useMart for more information
Calls: Main ... LoadGenomeAnnotation -> GetAnnotations -> getBM -> martCheck
In addition: Warning message:
Ensembl will soon enforce the use of https.
Ensure the 'host' argument includes "https://"
Execution halted

May I get your help? Thank you very much!

**Comment by paulati** [comment]
Hello willluo123,
the problem is that annotations from oct2018.archive.ensembl.org are not available now.
You can replace line 253 in plot2DO/config/annotation_config.yaml with the value host: https://jan2019.archive.ensembl.org
Please, let me know if it works.
Best, 
Paula

**Comment by willluo123** [comment]
Hi Paula,
I replaced the host in the annotation_config.yaml and it works.

Thank you very much!
Best,
Will Luo




| |
罗维翰
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 3/27/2024 03:06 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [rchereji/plot2DO] Error: Unexpected format to the list of available marts. (Issue #18) |

Hello willluo123,
the problem is that annotations from oct2018.archive.ensembl.org are not available now.
You can replace line 253 in plot2DO/config/annotation_config.yaml with the value host: https://jan2019.archive.ensembl.org
Please, let me know if it works.
Best,
Paula
