### ISSUE TITLE
Error in bmRequest(request = request, httr_config = httr_config, verbose = verbose) : Forbidden (HTTP 403)

### ISSUE THREAD

**Issue by MimArnold** [rchereji/plot2DO#19]
Hello, 

When running plot2DO with default parameters and hg38, I encounter the following warnings and errors: 

`Warning message:
package ‘ggplot2’ was built under R version 4.3.2 
Error in bmRequest(request = request, httr_config = httr_config, verbose = verbose) : 
  Forbidden (HTTP 403).
Calls: Main ... .useMart -> .listMarts -> bmRequest -> stop_for_status 
In addition: Warning message:
Ensembl will soon enforce the use of https.
Ensure the 'host' argument includes "https://" 
Execution halted`

I got those warnings before but the error seems to occur since last week only. 

Thanks in advance! 

Best,
Mim

**Comment by paulati** [comment]
Hello Mim, 
Can you try changing line 388 in this file?
https://github.com/rchereji/plot2DO/blob/master/config/annotation_config.yaml

Replacing 
host: jan2019.archive.ensembl.org 
by 
host: jul2019.archive.ensembl.org
can solve the problem.

Please let me know if the error persists.
Best,
Paula

**Comment by MimArnold** [comment]
Hi Paula, 

Yes, replacing that line solved the issue. Thanks a lot! 

Best, 
Mim

**Comment by paulati** [comment]
great, you're welcome!
