### ISSUE TITLE
Using custom list of genes rather than whole genome

### ISSUE THREAD

**Issue by ejwright39** [rchereji/plot2DO#2]
I'm interested in plotting nucleosome occupancy at specific target genes in response to an agonist vs vehicle. I have used plot2DO to generate a heatmap for occupancy for each treatment genome wide, however, for mice that is not too informative because the genome is so large. Is it possible to use a custom list of genes/annotations in bed format (or whatever relevant format) rather than the whole genome? 

Thanks!

**Comment by rchereji** [comment]
Sure, just use the `--sites/--align` options like this: `--sites=list_of_genes.BED --align=fivePrime`. For more options, check the help page (`Rscript plot2DO.R --help`).

**Comment by ejwright39** [comment]
I'll give it a try! Thank you for the quick reply!
