### ISSUE TITLE
hg19 annotations?

### ISSUE THREAD

**Issue by MagpiePKU** [rchereji/plot2DO#3]
Hi,

Could you please provide the hg19/hg38 annotations for use? We got problems accessing ensembl from time to time in China. Thanks a lot!

Best,
Yi

**Comment by rchereji** [comment]
Hi Yi,

Please try this workaround first: https://www.bioconductor.org/packages/devel/bioc/vignettes/biomaRt/inst/doc/biomaRt.html#connection-troubleshooting

Cc: @paulati
