### ISSUE TITLE
Is there any way to run it in parallel?

### ISSUE THREAD

**Issue by clouds-drift** [rchereji/plot2DO#4]
Hi rchereji,
I saw you installed the "foreach" package in the script.
Is there any way to run it in parallel by specify a thread number?

Best,
Xu

**Comment by paulati** [comment]
Hi Xu
the number of cores used is set here:
https://github.com/rchereji/plot2DO/blob/master/source/plot2DO_core.R, line 28:
 noCores <- min(noCores - 1, 8)
Best, 
Paula

**Comment by clouds-drift** [comment]
Yes, the script choose the threads number in a clever way.
many thanks!
