### ISSUE TITLE
Can I specify the absolute path for input an output?

### ISSUE THREAD

**Issue by clouds-drift** [rchereji/plot2DO#5]
Currently, I have to copy the infiles into the folder of the script and the output is also under the same folder.
Can I specify them by absolute path?

Best,
Xu

**Comment by paulati** [comment]
Hi Xu

If you want to specify absolute paths for source and destination folders, you can do it here modifying the values of reads and output
https://github.com/rchereji/plot2DO/blob/master/config/config.yaml

For instance:

application:
  paths:
    source: 
    # config:
    reads: /paula/bams/replica_2
    annotations:
    output: /paula/out/replica_2

Best,
Paula

**Comment by clouds-drift** [comment]
many thanks!
