### ISSUE TITLE
Hi! Developer! How can I use plot2DO for other species?Like maize?

### ISSUE THREAD

**Issue by chesterlee7246** [rchereji/plot2DO#6]

**Comment by rchereji** [comment]
Unfortunately, at this point the only supported species are S. cerevisiae, S. pombe, D. melanogaster, C. elegans, M. musculus, H. sapiens, and A. thaliana. To analyze sequencing data for other species you will have to ask "your bioinformatician" for a little help, to change the actual code -- it should be easy (just follow the template for the other species and add the required links to the annotations for to the new species)
