### ISSUE TITLE
error if using C elegans

### ISSUE THREAD

**Issue by Subhanita** [rchereji/plot2DO#7]
Hi,
I had following errors. could you please help?

Error in .normarg_seqlevels(seqnames) : 
  supplied 'seqlevels' cannot contain NAs or empty strings ("")
Calls: Main ... BuildReadsGRangesFromBAM -> Seqinfo -> .normarg_seqlevels
Execution halted

best
Su

**Comment by rchereji** [comment]
From your error message "supplied 'seqlevels' cannot contain NAs or empty strings ("")" it appears that your BAM file is corrupt and is missing some chromosome names (seqlevels). Please try plot2DO using another BAM file (e.g. the BAM files that we provided as examples) to make sure that you downloaded everything and plot2DO is working using a normal BAM file. Without your original BAM file that gives this error, I can't really tell the exact problem with your file.

**Comment by Subhanita** [comment]
hi, Thanks for your message.
My bed file looks like this:
chrV	11380838	11380938	D00467:395:CE7JDANXX:4:2309:1163:2165/1	42	+
chrV	11380893	11380993	D00467:395:CE7JDANXX:4:2309:1163:2165/2	42	-
chrX	10286716	10286816	D00467:395:CE7JDANXX:4:2309:1333:2116/1	42	-
chrX	10286707	10286807	D00467:395:CE7JDANXX:4:2309:1333:2116/2	42	+
will this work?
thanks 
Su

**Comment by Subhanita** [comment]
Hi,
Thanks for your suggestion. But I have another error now :(

Error in print_help(opt_parser) : object 'opt_parser' not found
Calls: Main -> LoadGenomeAnnotation_v2 -> print_help -> cat
Execution halted

Could you please help?
I have R version 4.0.0 (2020-04-24)

I have used .bdg file as input
chrI    0       265     0.00000
chrI    265     283     0.03407
chrI    283     289     0.06815
chrI    289     314     0.10222
chrI    314     318     0.13629

Thanks
Su

**Comment by paulati** [comment]
Hello Su, 
annotations are read from input bam file or from the file path specified by the genome (the key) in https://github.com/rchereji/plot2DO/blob/master/config/annotation_config.yaml. These files are expected to be csv or txt files. bdg format files should also be an accepted input.
I have tested plot2DO with R4.0 and everything is ok with bam file format as input. If you want to share with me your annotation file I can check it locally and answer with more detail.
Best, 
Paula

**Comment by Subhanita** [comment]
Hello again,
I am having trouble running drosophila samples. I tried with sample .bam provided with the code. It still provides error either dm3 or dm6. Can you please help.

$Rscript plot2DO.R --genome=dm3 --file=fly_SRR2038265.5M_reads.bam
**Error: Unexpected format to the list of available marts.
Please check the following URL manually, and try ?listMarts for advice.
http://dec2014.archive.ensembl.org:80/biomart/martservice?type=registry&requestid=biomaRt
Execution halted**

$ Rscript plot2DO.R --genome=dm6 --file=fly_SRR2038265.5M_reads.bam
**Error in .normarg_seqlevels(seqnames) : 
  supplied 'seqlevels' cannot contain NAs or empty strings ("")
Calls: Main ... BuildReadsGRangesFromBAM -> Seqinfo -> .normarg_seqlevels
Execution halted**

Thanks a lot
Su

**Comment by rchereji** [comment]
Hi Su,
I pushed an update and it should work now. It seems the old ensembl server for dm3 annotations stopped working so I had to update that in the annotation_config.yaml
Let us know if you still have problems running the demo example, after you pull the update.
Best,
Razvan

**Comment by Subhanita** [comment]
Hi Razvan,
Thanks for your help. 
I will update and let you know.
Best
Su

Subhanita Ghosh
subhanita.ghosh@gmail.com
