### ISSUE TITLE
A. thaliana genome and bam file format

### ISSUE THREAD

**Issue by Nur-Taz** [rchereji/plot2DO#8]
We have mapped A. thaliana single-end MNase-seq data using bowtie2, and we are trying to get the nucleosome profile using plot2DO. However, we are getting the following error:

Error in .replace_seqlevels_style(x_seqlevels, value) : 
  found no sequence renaming map compatible with seqname style "UCSC" for this object
Calls: Main ... seqlevelsStyle<- -> seqlevelsStyle<- -> .replace_seqlevels_style
Execution halted

1. Is this likely to be an issue with the bam file format? 
2. sacCer3 is the default annotation, but is A. thaliana annotation available with -g tair10, just like dm3, mm10 etc?

Really appreciate your help!

**Comment by paulati** [comment]
Hello Nur-Taz, I think that there is a problem with this config file
https://github.com/rchereji/plot2DO/blob/master/config/annotation_config.yaml (ctrl+f tair10)
tair10:
    chromosome_size: 
      url: https://genome-test.gi.ucsc.edu/~hiram/hubs/Plants/araTha1/araTha1.chrom.sizes
      filter:
        - 1
        - 2
        - 3
        - 4
        - 5
filter items should be replaced by chr1 chr2 ... exactly with the same names as here        
https://genome-test.gi.ucsc.edu/~hiram/hubs/Plants/araTha1/araTha1.chrom.sizes
If you modify this config file and it works, please let me know and I'll push this fix.
If it doesn't work and you can give me any link to any arabidopsis alignment that can be used for testing I will be glad to try to fix this.

**Comment by rchereji** [comment]
Moreover, if your bam file contains single-end reads, there's no way to obtain the length of each fragment. Plot2DO requires paired-end reads; only those contain information about the length of the sequenced fragments (the vertical axis of each heat map produced by plot2DO).

**Comment by Nur-Taz** [comment]
Thank-you very much @paulati and @rchereji. We will try out both (1) using a sample with paired-end reads and (2) changing the config file and let you know. Really appreciate your responses and input.

**Comment by rchereji** [comment]
I'll close this issue now, but feel free to open a new issue if you still have problems with the paired-end data. Good luck with your experiments!
