### ISSUE TITLE
Error in .replace-seqlevels_style

### ISSUE THREAD

**Issue by Nur-Taz** [rchereji/plot2DO#9]
Hello plot2DO team: We are trying to run plot2DO with paired-end bam files (Bowtie2 output) and tair10 (with and without changing the config file). I have attached screenshots of the error message and the changes we made in the config file. Are we missing something? We deeply appreciate your help, as always. 
![Screen Shot 2020-10-06 at 10 22 19 AM](https://user-images.githubusercontent.com/12501646/95240484-7c9f1f00-07da-11eb-9398-bfc05dda87f1.png)
![Screen Shot 2020-10-06 at 10 23 04 AM](https://user-images.githubusercontent.com/12501646/95240500-8032a600-07da-11eb-9cba-227744cdbebf.png)

**Comment by paulati** [comment]
hello Nur-Taz, I've just pushed a fix for tair10 seqnames, and config file shouldn't be changed now. I hope this helps you

**Comment by Nur-Taz** [comment]
Thanks @paulati. Let us try again and update you.

**Comment by Nur-Taz** [comment]
Our issue has been resolved. Thank-you very much for all the help!!!
